<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>CrazySnackRush</AssemblyName>
    <RootNamespace>CrazySnackRush</RootNamespace>
    <StartupObject>Program</StartupObject>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Optimize>false</Optimize>
  </PropertyGroup>

</Project>
